### ISSUE TITLE
Support config?

### ISSUE THREAD

**Issue by daniel-huang** [r3oath/hive#7]
Is it possible to support config to flexibly set up folder structure?

**Comment by r3oath** [comment]
It's possibly something I can introduce in a future release, do you have any particular requirements for your use case?

**Comment by daniel-huang** [comment]
For example, to support the folder structure for domain driven design.

**Comment by r3oath** [comment]
The majority of my domain driven framework code has moved over to [Enzyme/Axiom](https://github.com/enzyme/axiom) which now supports a configurable setup in terms of namespaces and file locations. Check it out if you're interested.
